# Generated by Django 2.1.1 on 2018-09-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CEA', 'Centro de Enseñanaza Automovilísitico'), ('CRC', 'Centro de Reconocimiento de Conductores'), ('CLI', 'Cliente'), ('EXU', 'Usuario express')], max_length=3, verbose_name='Tipo Usuario'),
        ),
    ]
