# Generated by Django 2.1.1 on 2018-09-13 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20180913_1012'),
        ('users', '0003_auto_20180912_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cea',
            field=models.ForeignKey(blank=True, help_text='Centro de Enseñanaza Automovilísitica que adminsitra el usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_ceas', to='companies.Cea', verbose_name='CEA del usuario'),
        ),
        migrations.AddField(
            model_name='user',
            name='crc',
            field=models.ForeignKey(blank=True, help_text='Centro de Reconocimiento de Conductores que adminsitra el usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_crcs', to='companies.Crc', verbose_name='CRC del usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('document_id', 'crc', 'email'), ('document_id', 'cea', 'email')},
        ),
    ]
