# Generated by Django 2.1.1 on 2018-09-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180913_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('MAN', 'Administrador de CEA o CRC'), ('CLI', 'Cliente'), ('EXU', 'Usuario express')], max_length=3, verbose_name='Tipo Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user',
            name='cea',
        ),
        migrations.RemoveField(
            model_name='user',
            name='crc',
        ),
    ]
