# Generated by Django 2.1.1 on 2018-09-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180913_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CEA', 'Administrador de CEA'), ('CRC', 'Administrador de CRC'), ('CLI', 'Cliente'), ('EXU', 'Usuario express')], max_length=3, verbose_name='Tipo Usuario'),
        ),
    ]
