# Generated by Django 2.1.1 on 2018-10-31 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181010_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_activation_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='Token recuperar contraseña')),
                ('is_use_token', models.BooleanField(default=False, verbose_name='Recuperó la contraseña?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
