# Generated by Django 2.1.1 on 2018-12-12 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_age', models.IntegerField(verbose_name='Edad inicial')),
                ('end_age', models.IntegerField(verbose_name='Edad final')),
            ],
            options={
                'verbose_name': 'Rango de edad',
                'verbose_name_plural': 'Rangos de edades',
            },
        ),
        migrations.CreateModel(
            name='AnsvRanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('age_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licences.AgeRange', verbose_name='Rango de edades')),
            ],
            options={
                'verbose_name': 'Valor de ANSV',
                'verbose_name_plural': 'Valores de ANSV',
            },
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3')], max_length=2, unique=True, verbose_name='Categoría')),
                ('description', models.TextField(verbose_name='Descripción de la categoría')),
            ],
            options={
                'verbose_name': 'Licencia',
            },
        ),
        migrations.AddField(
            model_name='ansvranges',
            name='licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licences.Licence', verbose_name='Licencia'),
        ),
        migrations.AlterUniqueTogether(
            name='ansvranges',
            unique_together={('licence', 'gender', 'age_range')},
        ),
    ]
