# Generated by Django 2.1.1 on 2018-09-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3')], max_length=2, unique=True, verbose_name='Categoría')),
                ('description', models.TextField(verbose_name='Descripción de la categoría')),
            ],
            options={
                'verbose_name': 'Licencia',
            },
        ),
    ]
