# Generated by Django 2.1.1 on 2018-10-01 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsvRanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género')),
                ('age_range', models.CharField(choices=[('16-26', 'Entre 16 y 25 años'), ('26-35', 'Entre 26 y 35 años'), ('36-50', 'Entre 36 y 50 años'), ('51-65', 'Entre 51 y 65 años'), ('66-80', 'Entre 66 y 80 años'), ('81-99', 'desde 81 años en adelante')], max_length=5, verbose_name='Rango de edades')),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licences.Licence', verbose_name='Licencia')),
            ],
            options={
                'verbose_name': 'Valor de ANSV',
                'verbose_name_plural': 'Valores de ANSV',
            },
        ),
    ]
