# Generated by Django 2.1.1 on 2018-10-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0002_ansvranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansvranges',
            name='price',
            field=models.CharField(default=0, max_length=10, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
