# Generated by Django 2.1.1 on 2018-10-01 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0004_auto_20181001_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_age', models.CharField(max_length=3, verbose_name='Edad inicial')),
                ('end_age', models.CharField(max_length=3, verbose_name='Edad final')),
            ],
            options={
                'verbose_name': 'Rango de edad',
                'verbose_name_plural': 'Rangos de edades',
            },
        ),
        migrations.AlterField(
            model_name='ansvranges',
            name='age_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licences.AgeRange', verbose_name='Rango de edades'),
        ),
    ]
