# Generated by Django 2.1.1 on 2018-10-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0006_auto_20181004_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansvranges',
            name='price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
