# Generated by Django 2.1.1 on 2018-12-12 21:20

import companies.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('nit', models.CharField(help_text='El nit puede llevar el digito de verificación', max_length=15, verbose_name='Nit')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, help_text='Opcional. Sin indicativo de área', max_length=7, null=True, verbose_name='Teléfono Fijo')),
                ('cellphone', models.CharField(max_length=10, verbose_name='Celular')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=companies.utils.get_upload_to, verbose_name='logo de la empresa')),
                ('rating', models.FloatField(default=0, verbose_name='Calificación Promedio')),
                ('schedule', models.TextField(help_text='Ejm: De lunes a viernes de 8:00 am a 6:00 pm', verbose_name='Horarios de atención administrativo')),
                ('courses_schedule', models.TextField(help_text='Ejm: De lunes a viernes de 8:00 am a 6:00 pm', verbose_name='Horarios de atención para cursos')),
            ],
            options={
                'verbose_name': 'Centro de Enseñanaza Automovilísitico',
                'verbose_name_plural': 'Centros de Enseñanaza Automovilísiticos',
            },
        ),
        migrations.CreateModel(
            name='CeaLicence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(help_text='Precio de la licencia nueva', verbose_name='Precio')),
                ('price_recat', models.IntegerField(help_text='Precio de la licencia para recategorización', verbose_name='Precio recategorización')),
                ('theoretical_classes', models.IntegerField(verbose_name='Número de clases teóricas')),
                ('practical_classes', models.IntegerField(verbose_name='Número de clases prácticas')),
                ('mechanical_classes', models.IntegerField(verbose_name='Número de clases de Taller')),
            ],
            options={
                'verbose_name': 'Licencia de Cea',
                'verbose_name_plural': 'Licencias de los Cea',
            },
        ),
        migrations.CreateModel(
            name='CeaRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(default='N/A', null=True)),
                ('stars', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Calificacion CEA',
                'verbose_name_plural': 'Calificaciones CEA',
            },
        ),
        migrations.CreateModel(
            name='CeaVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(help_text='ABC 123', max_length=7, unique=True, verbose_name='Placa')),
                ('model', models.CharField(help_text='2008', max_length=4, verbose_name='Modelo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activo?')),
            ],
            options={
                'verbose_name': 'Vehículos del CEA',
            },
        ),
        migrations.CreateModel(
            name='Crc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('nit', models.CharField(help_text='El nit puede llevar el digito de verificación', max_length=15, verbose_name='Nit')),
                ('price', models.IntegerField(help_text='Precio del servicio para una sola licencia', verbose_name='Precio del servicio')),
                ('price_double', models.IntegerField(help_text='Precio del servicio para 2 licencias', verbose_name='Precio del servicio doble')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, help_text='Opcional. Sin indicativo de área', max_length=7, null=True, verbose_name='Teléfono Fijo')),
                ('cellphone', models.CharField(max_length=10, verbose_name='Celular')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=companies.utils.get_upload_to, verbose_name='logo de la empresa')),
                ('rating', models.FloatField(default=0, verbose_name='Calificación Promedio')),
                ('schedule', models.TextField(help_text='Ejm: De lunes a viernes de 8:00 am a 6:00 pm', verbose_name='Horarios de atención')),
            ],
            options={
                'verbose_name': 'Centro de Reconocimiento de Conductores',
                'verbose_name_plural': 'Centros de Reconocimiento de Conductores',
            },
        ),
        migrations.CreateModel(
            name='CrcRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(default='N/A', null=True)),
                ('stars', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Calificacion CRC',
                'verbose_name_plural': 'Calificaciones CRC',
            },
        ),
        migrations.CreateModel(
            name='TransitDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('nit', models.CharField(help_text='El nit puede llevar el digito de verificación', max_length=15, verbose_name='Nit')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, help_text='Opcional. Sin indicativo de área', max_length=7, null=True, verbose_name='Teléfono Fijo')),
                ('cellphone', models.CharField(max_length=10, verbose_name='Celular')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=companies.utils.get_upload_to, verbose_name='logo de la empresa')),
                ('rating', models.FloatField(default=0, verbose_name='Calificación Promedio')),
                ('schedule', models.TextField(help_text='Ejm: De lunes a viernes de 8:00 am a 6:00 pm', verbose_name='Horarios de atención')),
            ],
            options={
                'verbose_name': 'Departamento de Tránsito',
                'verbose_name_plural': 'Departamentos de Tránsito',
            },
        ),
        migrations.CreateModel(
            name='TransitRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(default='N/A', null=True)),
                ('stars', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Calificacion Organismo de transporte',
                'verbose_name_plural': 'Calificaciones Organismo de transporte',
            },
        ),
        migrations.CreateModel(
            name='TuLicencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, help_text='Opcional. Sin indicativo de área', max_length=7, null=True, verbose_name='Teléfono fijo')),
                ('cellphone', models.CharField(max_length=10, verbose_name='Celular')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.City', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Punto TuLicencia',
                'verbose_name_plural': 'Puntos TuLicencia',
            },
        ),
    ]
