# Generated by Django 2.1.1 on 2018-09-12 18:15

import companies.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('nit', models.CharField(help_text='El nit puede llevar el digito de verificación', max_length=15, verbose_name='Nit')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, help_text='Opcional. Sin indicativo de área', max_length=7, null=True, verbose_name='Teléfono Fijo')),
                ('cellphone', models.CharField(max_length=10, verbose_name='Celular')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=companies.utils.get_upload_to, verbose_name='logo de la empresa')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.City', verbose_name='Ciudad')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.State', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Centro de Enseñanaza Automovilísitico',
                'verbose_name_plural': 'Centros de Enseñanaza Automovilísiticos',
            },
        ),
        migrations.CreateModel(
            name='Crc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('nit', models.CharField(help_text='El nit puede llevar el digito de verificación', max_length=15, verbose_name='Nit')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, help_text='Opcional. Sin indicativo de área', max_length=7, null=True, verbose_name='Teléfono Fijo')),
                ('cellphone', models.CharField(max_length=10, verbose_name='Celular')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=companies.utils.get_upload_to, verbose_name='logo de la empresa')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.City', verbose_name='Ciudad')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.State', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Centro de Reconocimiento de Conductores',
                'verbose_name_plural': 'Centros de Reconocimiento de Conductores',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(verbose_name='Dia')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de cierre')),
                ('journey', models.CharField(choices=[('J1', 'Jornada 1'), ('J2', 'Jornada 2')], default='J1', max_length=2, verbose_name='Jornada')),
                ('cea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_schedules', to='companies.Cea', verbose_name='Centro de Enseñanaza Automovilísitico')),
                ('crc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_schedules', to='companies.Crc', verbose_name='Centro de Reconocimiento de Conductores')),
            ],
            options={
                'verbose_name': 'Horario',
            },
        ),
        migrations.CreateModel(
            name='TransitDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('nit', models.CharField(help_text='El nit puede llevar el digito de verificación', max_length=15, verbose_name='Nit')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, help_text='Opcional. Sin indicativo de área', max_length=7, null=True, verbose_name='Teléfono Fijo')),
                ('cellphone', models.CharField(max_length=10, verbose_name='Celular')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=companies.utils.get_upload_to, verbose_name='logo de la empresa')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.City', verbose_name='Ciudad')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.State', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Departamento de Tránsito',
                'verbose_name_plural': 'Departamentos de Tránsito',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='transit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_schedules', to='companies.TransitDepartment', verbose_name='Departamento de Tránsito'),
        ),
    ]
