# Generated by Django 2.1.1 on 2018-12-12 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0001_initial'),
        ('licences', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tulicencia',
            name='express_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Express'),
        ),
        migrations.AddField(
            model_name='tulicencia',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.State', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='transitrating',
            name='transit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_ratings', to='companies.TransitDepartment', verbose_name='Organismo de transporte'),
        ),
        migrations.AddField(
            model_name='transitrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_transit_user_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='transitdepartment',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.City', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='transitdepartment',
            name='prices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.TransitDepartmentPrices', verbose_name='Precios organismo de transito'),
        ),
        migrations.AddField(
            model_name='transitdepartment',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.Sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='transitdepartment',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.State', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='crcrating',
            name='crc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crc_ratings', to='companies.Crc', verbose_name='Crc'),
        ),
        migrations.AddField(
            model_name='crcrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_crc_user_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='crc',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.City', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='crc',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.CompaniesAdminPrices', verbose_name='Pin sicov y recaudo banco'),
        ),
        migrations.AddField(
            model_name='crc',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='crc',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='manager.Sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='crc',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.State', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='ceavehicle',
            name='cea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='companies.Cea', verbose_name='CEA'),
        ),
        migrations.AddField(
            model_name='ceavehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle', verbose_name='Vehículo'),
        ),
        migrations.AddField(
            model_name='cearating',
            name='cea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cea_ratings', to='companies.Cea', verbose_name='Cea'),
        ),
        migrations.AddField(
            model_name='cearating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_cea_user_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='cealicence',
            name='cea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licences', to='companies.Cea', verbose_name='CEA'),
        ),
        migrations.AddField(
            model_name='cealicence',
            name='licence',
            field=models.ForeignKey(help_text='Selecciona las licencias disponibles en el CEA', on_delete=django.db.models.deletion.CASCADE, to='licences.Licence', verbose_name='Licencias'),
        ),
        migrations.AddField(
            model_name='cea',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.City', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='cea',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.CompaniesAdminPrices', verbose_name='Pin sicov y recaudo banco'),
        ),
        migrations.AddField(
            model_name='cea',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='cea',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.Sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='cea',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.State', verbose_name='Departamento'),
        ),
    ]
