# Generated by Django 2.1.1 on 2018-09-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crc',
            name='price',
            field=models.CharField(default=0, max_length=7, verbose_name='Precio del servicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crc',
            name='price_double',
            field=models.CharField(default='0', max_length=7, verbose_name='Precio del servicio doble'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], max_length=1, verbose_name='Dia'),
        ),
    ]
