# Generated by Django 2.1.1 on 2018-12-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20181212_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='cea',
            name='epayco_code',
            field=models.CharField(default='11736', max_length=10, verbose_name='Codigo ePayco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crc',
            name='epayco_code',
            field=models.CharField(default='11736', max_length=10, verbose_name='Codigo ePayco'),
            preserve_default=False,
        ),
    ]
