# Generated by Django 2.1.1 on 2018-09-13 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0001_initial'),
        ('vehicles', '0002_vehicle_licences'),
        ('companies', '0002_auto_20180912_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeaLicence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(help_text='Precio de la licencia nueva', max_length=255, verbose_name='Precio')),
                ('price_recat', models.CharField(help_text='Precio de la licencia para recategorización', max_length=255, verbose_name='Precio recategorización')),
                ('cea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Cea', verbose_name='CEA')),
                ('licence', models.ManyToManyField(help_text='Selecciona una o varias licencias disponibles para el CEA', to='licences.Licence', verbose_name='Licencias')),
            ],
            options={
                'verbose_name': 'Licencia de Cea',
                'verbose_name_plural': 'Licencias de los Cea',
            },
        ),
        migrations.CreateModel(
            name='CeaVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Cea', verbose_name='CEA')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Vehículos del CEA',
            },
        ),
    ]
