# Generated by Django 2.1.1 on 2018-09-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_cealicence_ceavehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceavehicle',
            name='badge',
            field=models.CharField(default='ABC 123', help_text='ABC 123', max_length=7, verbose_name='Placa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ceavehicle',
            name='model',
            field=models.CharField(default='1992', help_text='2008', max_length=4, verbose_name='Modelo'),
            preserve_default=False,
        ),
    ]
