# Generated by Django 2.1.1 on 2019-01-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20190123_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cearating',
            name='detail',
            field=models.TextField(blank=True, default='N/A', null=True, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='crcrating',
            name='detail',
            field=models.TextField(blank=True, default='N/A', null=True, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='transitrating',
            name='detail',
            field=models.TextField(blank=True, default='N/A', null=True, verbose_name='Detalle'),
        ),
    ]
