# Generated by Django 2.1.1 on 2018-09-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20180913_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceavehicle',
            name='badge',
            field=models.CharField(help_text='ABC 123', max_length=7, unique=True, verbose_name='Placa'),
        ),
    ]
