# Generated by Django 2.1.1 on 2019-02-05 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0001_initial'),
        ('companies', '0005_auto_20190124_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramit', models.CharField(choices=[('IN', 'Licencia inicial'), ('RE', 'Recategorización'), ('RN', 'Renovación')], max_length=2, verbose_name='Trámite')),
                ('runt_price', models.IntegerField(verbose_name='Precio del RUNT')),
                ('simple_print_price', models.IntegerField(verbose_name='Precio de impresión sencillo')),
                ('double_print_price', models.IntegerField(verbose_name='Precio de impresión doble')),
                ('other_price', models.IntegerField(verbose_name='Otros precios')),
                ('licences', models.ManyToManyField(to='licences.Licence', verbose_name='Licencias')),
                ('transit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_transit', to='companies.TransitDepartment', verbose_name='Departamento de tránsito')),
            ],
            options={
                'verbose_name': 'Precio del departamento de tránsito',
                'verbose_name_plural': 'Precios del departamento de tránsito',
            },
        ),
    ]
