# Generated by Django 2.1.1 on 2018-09-13 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0001_initial'),
        ('companies', '0005_auto_20180913_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cealicence',
            name='licence',
        ),
        migrations.AddField(
            model_name='cealicence',
            name='licence',
            field=models.ForeignKey(default='1', help_text='Selecciona las licencias disponibles en el CEA', on_delete=django.db.models.deletion.CASCADE, to='licences.Licence', verbose_name='Licencias'),
            preserve_default=False,
        ),
    ]
