# Generated by Django 2.1.1 on 2018-09-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20180913_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='cealicence',
            name='mechanical_classes',
            field=models.IntegerField(default='0', verbose_name='Número de clases de Taller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cealicence',
            name='practical_classes',
            field=models.IntegerField(default='0', verbose_name='Número de clases prácticas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cealicence',
            name='service',
            field=models.CharField(choices=[('IL', 'Licencia Inicial'), ('RL', 'Recategorización hacia arriba')], default='0', help_text='Selecciona para que servicio es esta licencia', max_length=2, verbose_name='Servicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cealicence',
            name='theoretical_classes',
            field=models.IntegerField(default='0', verbose_name='Número de clases teóricas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crc',
            name='price',
            field=models.CharField(help_text='Precio del servicio para una sola licencia', max_length=7, verbose_name='Precio del servicio'),
        ),
        migrations.AlterField(
            model_name='crc',
            name='price_double',
            field=models.CharField(help_text='Precio del servicio para 2 licencias', max_length=7, verbose_name='Precio del servicio doble'),
        ),
    ]
