# Generated by Django 2.1.1 on 2019-02-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_transitprices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitprices',
            name='tramit',
            field=models.CharField(choices=[('IN', 'Licencia inicial'), ('RC', 'Recategorización'), ('RN', 'Renovación')], max_length=2, verbose_name='Trámite'),
        ),
    ]
