# Generated by Django 2.1.1 on 2018-09-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20180913_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cealicence',
            name='service',
        ),
    ]
