# Generated by Django 2.1.1 on 2018-09-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20180913_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cea',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='crc',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='transitdepartment',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
    ]
