# Generated by Django 2.1.1 on 2018-09-20 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_tulicencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cealicence',
            name='licence',
            field=models.ForeignKey(help_text='Selecciona las licencias disponibles en el CEA', on_delete=django.db.models.deletion.CASCADE, related_name='licences', to='licences.Licence', verbose_name='Licencias'),
        ),
        migrations.AlterField(
            model_name='ceavehicle',
            name='cea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_vehicles', to='companies.Cea', verbose_name='CEA'),
        ),
    ]
