# Generated by Django 2.1.1 on 2018-10-01 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0001_initial'),
        ('companies', '0015_auto_20181001_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitLicence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(help_text='Precio de la licencia nueva', max_length=255, verbose_name='Precio')),
                ('licence', models.ForeignKey(help_text='Selecciona la licencia', on_delete=django.db.models.deletion.CASCADE, to='licences.Licence', verbose_name='Licencias')),
                ('transit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_licences', to='companies.TransitDepartment', verbose_name='Oficina de Tránsito')),
            ],
            options={
                'verbose_name': 'Precio de licencia de tránsito',
                'verbose_name_plural': 'Precios de licencias de tránsito',
            },
        ),
    ]
