# Generated by Django 2.1.1 on 2018-10-03 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_crcadminprices'),
        ('companies', '0016_transitlicence'),
    ]

    operations = [
        migrations.AddField(
            model_name='crc',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.CRCAdminPrices', verbose_name='Pin sicov y recaudo banco'),
        ),
    ]
