# Generated by Django 2.1.1 on 2018-10-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_crc_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitdepartment',
            name='runt_price',
            field=models.CharField(default='0', max_length=255, verbose_name='Precio del RUNT'),
            preserve_default=False,
        ),
    ]
