# Generated by Django 2.1.1 on 2018-10-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_auto_20181004_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='cea',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crc',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transitdepartment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
