# Generated by Django 2.1.1 on 2018-10-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_tulicencia_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceavehicle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
