# Generated by Django 2.1.1 on 2018-10-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_ceavehicle_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceavehicle',
            name='deleted_at',
        ),
    ]
