# Generated by Django 2.1.1 on 2018-10-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_cearating_crcrating_transitrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cea',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='crc',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='transitdepartment',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='tulicencia',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
