# Generated by Django 2.1.1 on 2018-10-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_sector'),
        ('companies', '0025_auto_20181010_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='cea',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.Sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='crc',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.Sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='transitdepartment',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.Sector', verbose_name='Sector'),
        ),
    ]
