# Generated by Django 2.1.1 on 2018-10-11 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_auto_20181010_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cearating',
            name='cea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cea_ratings', to='companies.Cea', verbose_name='Cea'),
        ),
        migrations.AlterField(
            model_name='crcrating',
            name='crc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crc_ratings', to='companies.Crc', verbose_name='Crc'),
        ),
        migrations.AlterField(
            model_name='transitrating',
            name='transit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_ratings', to='companies.TransitDepartment', verbose_name='Organismo de transporte'),
        ),
    ]
