# Generated by Django 2.1.1 on 2018-10-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_auto_20181011_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crc',
            name='collection',
        ),
    ]
