# Generated by Django 2.1.1 on 2018-10-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0031_cea_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='cea',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='crc',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='transit',
        ),
        migrations.AddField(
            model_name='cea',
            name='schedule',
            field=models.TextField(default='', help_text='Ejm: De lunes a viernes de 8:00 am a 6:00 pm', verbose_name='Horarios de atención'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crc',
            name='schedule',
            field=models.TextField(default='.', help_text='Ejm: De lunes a viernes de 8:00 am a 6:00 pm', verbose_name='Horarios de atención'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transitdepartment',
            name='schedule',
            field=models.TextField(default='0', help_text='Ejm: De lunes a viernes de 8:00 am a 6:00 pm', verbose_name='Horarios de atención'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
