# Generated by Django 2.1.1 on 2018-10-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0032_auto_20181016_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cealicence',
            name='price',
            field=models.IntegerField(help_text='Precio de la licencia nueva', verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='cealicence',
            name='price_recat',
            field=models.IntegerField(help_text='Precio de la licencia para recategorización', verbose_name='Precio recategorización'),
        ),
    ]
