# Generated by Django 2.1.1 on 2018-10-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0033_auto_20181017_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='cea',
            name='courses_schedule',
            field=models.TextField(default='0', help_text='Ejm: De lunes a viernes de 8:00 am a 6:00 pm', verbose_name='Horarios de atención para cursos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cea',
            name='schedule',
            field=models.TextField(help_text='Ejm: De lunes a viernes de 8:00 am a 6:00 pm', verbose_name='Horarios de atención administrativo'),
        ),
    ]
