# Generated by Django 2.1.1 on 2018-11-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_auto_20181022_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceavehicle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Esta activo?'),
        ),
    ]
