# Generated by Django 2.1.1 on 2018-11-27 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_transitdepartmentprices_name'),
        ('companies', '0035_ceavehicle_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitdepartment',
            name='runt_price',
        ),
        migrations.AddField(
            model_name='transitdepartment',
            name='prices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.TransitDepartmentPrices', verbose_name='Precios organismo de transito'),
        ),
    ]
