# Generated by Django 2.1.1 on 2018-11-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0036_auto_20181127_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitlicence',
            name='licence',
        ),
        migrations.RemoveField(
            model_name='transitlicence',
            name='transit',
        ),
        migrations.DeleteModel(
            name='TransitLicence',
        ),
    ]
