# Generated by Django 2.1.1 on 2018-12-07 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0037_auto_20181127_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crc',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='manager.Sector', verbose_name='Sector'),
        ),
    ]
