# Generated by Django 2.1.1 on 2018-12-12 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licences', '0001_initial'),
        ('manager', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDocsStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('status', models.CharField(max_length=255, verbose_name='Estado')),
                ('transaction_manager', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsable de la operación')),
            ],
            options={
                'verbose_name': 'Log Estado de la documentación',
                'verbose_name_plural': 'Logs de estados de la documentación',
            },
        ),
        migrations.CreateModel(
            name='LogRequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('status', models.CharField(max_length=255, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Log Estado de la solicitud',
                'verbose_name_plural': 'Logs de estados de la solicitud',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=0, verbose_name='Precio total')),
                ('cea_status', models.CharField(choices=[('NS', 'Sin iniciar'), ('ST', 'Iniciado'), ('FN', 'Finalizado')], default='NS', max_length=2, verbose_name='Estado trámite en el cea')),
                ('crc_status', models.CharField(choices=[('NS', 'Sin iniciar'), ('ST', 'Iniciado'), ('FN', 'Finalizado')], default='NS', max_length=2, verbose_name='Estado trámite en el crc')),
                ('payment_type', models.CharField(choices=[('CR', 'Sistecrédito'), ('CO', 'Contado')], max_length=2, verbose_name='Tipo de pago')),
                ('request_status', models.CharField(choices=[('PEN', 'Pendiente'), ('PAI', 'Pagado'), ('CAN', 'En solicitud de cancelación'), ('ICRC', 'En exámen CRC'), ('ICEA', 'En curso CEA'), ('FNS', 'Finalizado')], default='PEN', max_length=4, verbose_name='Estado de la reserva')),
                ('docs_status', models.CharField(choices=[('PEN', 'Pendiente'), ('ILIQU', 'En liquidación'), ('PSUCC', 'Pagos realizados'), ('PRETU', 'Pagos retornados'), ('DSEND', 'Documentación enviada'), ('DDELI', 'Documentación entregada'), ('DRETU', 'Documentación retornada')], default='PEN', max_length=5, verbose_name='Estado de la documentación')),
                ('credit_status', models.CharField(choices=[('AC', 'Aceptado'), ('RE', 'Rechazado'), ('PA', 'Pendiente de aprobación'), ('NA', 'No aplica')], default='NA', max_length=2, verbose_name='Estado del crédito (si aplica)')),
                ('credit_request_code', models.CharField(blank=True, help_text='Código del crédito (Systecrédito)', max_length=255, null=True, verbose_name='Código solicitud del crédito (si aplica)')),
                ('booking', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de reserva')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la solicitud')),
                ('has_runt', models.BooleanField(default=False, verbose_name='Tiene RUNT?')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago de la solicitud')),
                ('payment_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado del pago')),
                ('id_invoice', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia de pago')),
                ('id_epayco_invoice', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia de pago de ePayco')),
                ('cea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_cea_requests', to='companies.Cea', verbose_name='CEA')),
                ('crc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_crc_requests', to='companies.Crc', verbose_name='CRC')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.State', verbose_name='Departamento')),
                ('transit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.TransitDepartment', verbose_name='Departamento de Tránsito')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='RequestTramit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramit_type', models.CharField(choices=[('FL', 'Primera Licencia'), ('SL', 'Segunda Licencia'), ('RN', 'Renovación'), ('RC', 'Recategorización'), ('DU', 'Duplicado')], max_length=2, verbose_name='Tipo de Trámite')),
                ('licence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licences.Licence', verbose_name='Licencia')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_tramits', to='request.Request', verbose_name='Trámites')),
            ],
            options={
                'verbose_name': 'Tramite',
            },
        ),
    ]
