# Generated by Django 2.1.1 on 2018-09-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0001_initial'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='licences',
            field=models.ManyToManyField(related_name='related_licences', to='licences.Licence', verbose_name='Licencias solicitadas'),
        ),
    ]
