# Generated by Django 2.1.1 on 2018-12-12 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_requests', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='logrequeststatus',
            name='request_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Request', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='logdocsstatus',
            name='process_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable del proceso'),
        ),
        migrations.AddField(
            model_name='logdocsstatus',
            name='request_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Request', verbose_name='Solicitud'),
        ),
    ]
