# Generated by Django 2.1.1 on 2018-09-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_request_licences'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('AC', 'Aceptado'), ('AT', 'Atendido'), ('PE', 'Pendiente')], default='0', max_length=2, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
