# Generated by Django 2.1.1 on 2018-09-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='credit_status',
            field=models.CharField(choices=[('AC', 'Aceptado'), ('RE', 'Rechazado'), ('PA', 'Pendiente de aprobación'), ('NA', 'No aplica')], default='0', max_length=2, verbose_name='Estado del crédito (si aplica)'),
            preserve_default=False,
        ),
    ]
