# Generated by Django 2.1.1 on 2018-12-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_request_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='payment_type2',
            field=models.CharField(blank=True, choices=[('CR', 'Sistecrédito'), ('CO', 'Contado'), ('TA', 'Tarjeta')], max_length=2, null=True, verbose_name='Tipo de pago secundario'),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor del pago secundario'),
        ),
        migrations.AlterField(
            model_name='request',
            name='payment_type',
            field=models.CharField(choices=[('CR', 'Sistecrédito'), ('CO', 'Contado'), ('TA', 'Tarjeta')], max_length=2, verbose_name='Tipo de pago'),
        ),
    ]
