# Generated by Django 2.1.1 on 2018-09-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_request_credit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='booking',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de reserva'),
        ),
        migrations.AddField(
            model_name='request',
            name='credit_request_code',
            field=models.CharField(blank=True, help_text='Código del crédito (Systecrédito)', max_length=255, null=True, verbose_name='Código solicitud del crédito (si aplica)'),
        ),
    ]
