# Generated by Django 2.1.1 on 2018-12-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20181225_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='payment_value2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor del pago secundario'),
        ),
        migrations.AlterField(
            model_name='request',
            name='payment_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor del pago'),
        ),
    ]
