# Generated by Django 2.1.1 on 2018-09-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20180920_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='credit_status',
            field=models.CharField(choices=[('AC', 'Aceptado'), ('RE', 'Rechazado'), ('PA', 'Pendiente de aprobación'), ('NA', 'No aplica')], default='NA', max_length=2, verbose_name='Estado del crédito (si aplica)'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('AC', 'Aceptado'), ('AT', 'Atendido'), ('PE', 'Pendiente')], default='PE', max_length=2, verbose_name='Estado'),
        ),
    ]
