# Generated by Django 2.1.1 on 2019-02-08 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0005_auto_20181225_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_exp_requests', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó la solicitud'),
        ),
    ]
