# Generated by Django 2.1.1 on 2018-10-01 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_auto_20180920_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='cea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_cea_requests', to='companies.Cea', verbose_name='CEA'),
        ),
        migrations.AlterField(
            model_name='request',
            name='crc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_crc_requests', to='companies.Crc', verbose_name='CRC'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_requests', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
    ]
