# Generated by Django 2.1.1 on 2018-10-01 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_auto_20181001_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de la solicitud'),
            preserve_default=False,
        ),
    ]
