# Generated by Django 2.1.1 on 2018-10-02 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_request_request_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDocsStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('status', models.CharField(max_length=255, verbose_name='Estado')),
                ('manager', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsable de la documentación')),
            ],
            options={
                'verbose_name': 'Log Estado de la solicitud',
                'verbose_name_plural': 'Logs de estados de la solicitud',
            },
        ),
        migrations.CreateModel(
            name='LogRequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('status', models.CharField(max_length=255, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Log Estado de la solicitud',
                'verbose_name_plural': 'Logs de estados de la solicitud',
            },
        ),
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
        migrations.AddField(
            model_name='request',
            name='cea_status',
            field=models.CharField(choices=[('NS', 'Sin iniciar'), ('ST', 'Iniciado'), ('FN', 'Finalizado')], default='NS', max_length=2, verbose_name='Estado trámite en el cea'),
        ),
        migrations.AddField(
            model_name='request',
            name='crc_status',
            field=models.CharField(choices=[('NS', 'Sin iniciar'), ('ST', 'Iniciado'), ('FN', 'Finalizado')], default='NS', max_length=2, verbose_name='Estado trámite en el crc'),
        ),
        migrations.AddField(
            model_name='request',
            name='docs_status',
            field=models.CharField(choices=[('ILIQU', 'En liquidación'), ('PSUCC', 'Pagos realizados'), ('PRETU', 'Pagos retornados'), ('DSEND', 'Documentación enviada'), ('DDELI', 'Documentación entregada'), ('DRETU', 'Documentación retornada')], default='PEN', max_length=5, verbose_name='Estado de la documentación'),
        ),
        migrations.AddField(
            model_name='request',
            name='request_status',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('PAI', 'Pagado'), ('ICRC', 'En exámen CRC'), ('ICEA', 'En curso CEA'), ('FNS', 'Finalizado')], default='PEN', max_length=4, verbose_name='Estado de la reserva'),
        ),
        migrations.AddField(
            model_name='logrequeststatus',
            name='request_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Request', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='logdocsstatus',
            name='request_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Request', verbose_name='Solicitud'),
        ),
    ]
