# Generated by Django 2.1.1 on 2018-10-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_auto_20181002_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='docs_status',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('ILIQU', 'En liquidación'), ('PSUCC', 'Pagos realizados'), ('PRETU', 'Pagos retornados'), ('DSEND', 'Documentación enviada'), ('DDELI', 'Documentación entregada'), ('DRETU', 'Documentación retornada')], default='PEN', max_length=5, verbose_name='Estado de la documentación'),
        ),
    ]
