# Generated by Django 2.1.1 on 2018-10-16 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0011_request_has_runt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logdocsstatus',
            name='manager',
        ),
        migrations.AddField(
            model_name='logdocsstatus',
            name='process_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete='Responsable del proceso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logdocsstatus',
            name='transaction_manager',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsable de la operación'),
        ),
    ]
