# Generated by Django 2.1.1 on 2018-10-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_auto_20181016_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Precio total'),
        ),
    ]
