# Generated by Django 2.1.1 on 2018-10-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0015_requesttramit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requesttramit',
            options={'verbose_name': 'Tramite'},
        ),
        migrations.RemoveField(
            model_name='request',
            name='licences',
        ),
    ]
