# Generated by Django 2.1.1 on 2018-10-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0016_auto_20181019_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='id_epayco_invoice',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia de pago de ePayco'),
        ),
        migrations.AddField(
            model_name='request',
            name='id_invoice',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia de pago'),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago de la solicitud'),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado del pago'),
        ),
    ]
