# Generated by Django 2.1.1 on 2018-11-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0017_auto_20181030_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttramit',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_tramits', to='request.Request', verbose_name='Trámites'),
        ),
    ]
