# Generated by Django 2.1.1 on 2018-11-21 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_contactform'),
        ('request', '0018_auto_20181109_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.State', verbose_name='Departamento'),
        ),
    ]
