# Generated by Django 2.1.1 on 2018-12-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0019_request_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_status',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('PAI', 'Pagado'), ('CAN', 'Solicitar cancelacion'), ('ICRC', 'En exámen CRC'), ('ICEA', 'En curso CEA'), ('FNS', 'Finalizado')], default='PEN', max_length=4, verbose_name='Estado de la reserva'),
        ),
    ]
