# Generated by Django 2.1.1 on 2018-12-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0020_auto_20181201_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_status',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('PAI', 'Pagado'), ('CAN', 'En solicitud de cancelación'), ('ICRC', 'En exámen CRC'), ('ICEA', 'En curso CEA'), ('FNS', 'Finalizado')], default='PEN', max_length=4, verbose_name='Estado de la reserva'),
        ),
    ]
