# Generated by Django 2.1.1 on 2018-09-13 09:31

from django.db import migrations, models
import django.db.models.deletion
import vehicles.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kia, Chevrolet, Renault...', max_length=255, verbose_name='Nombre de la marca')),
            ],
            options={
                'verbose_name': 'Marca de vehículo',
                'verbose_name_plural': 'Marcas de vehículo',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(help_text='Picanto, Spark GT, Clio, Twingo....', max_length=255, verbose_name='Linea del vehículo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Brand', verbose_name='Marca del vehículo')),
            ],
            options={
                'verbose_name': 'Vehículo',
            },
        ),
        migrations.CreateModel(
            name='VehicleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=vehicles.utils.get_upload_to, verbose_name='Imágen')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Imagen de vehículo',
                'verbose_name_plural': 'Imágenes de vechículos',
            },
        ),
    ]
