# Generated by Django 2.1.1 on 2018-09-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='licences',
            field=models.ManyToManyField(help_text='Escoga una o varias licencias válidas para éste vehículo', to='licences.Licence', verbose_name='Licencias'),
        ),
    ]
