# Generated by Django 2.1.1 on 2018-09-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_licences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimages',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.Vehicle', verbose_name='Vehículo'),
        ),
    ]
