# Generated by Django 2.1.1 on 2018-10-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20180920_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
