# Generated by Django 2.1.1 on 2018-12-12 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=4, null=True, verbose_name='Código')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='CompaniesAdminPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_sicov', models.IntegerField(verbose_name='Precio PIN SICOV')),
                ('recaudo', models.IntegerField(verbose_name='Precio Recaudo Banco')),
                ('supplier', models.CharField(default='', max_length=255, verbose_name='Proveedor')),
                ('company', models.CharField(choices=[('CEA', 'Centro de enseñanza automovilístico'), ('CRC', 'Centro de reconocimiento de conductores')], default='CRC', max_length=3, verbose_name='Compañía')),
            ],
            options={
                'verbose_name': 'Adminsitración Recaudo',
                'verbose_name_plural': 'Administración Recaudos',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('email', models.CharField(max_length=255, verbose_name='Correo')),
                ('contact_type', models.CharField(choices=[('PE', 'Petición'), ('QU', 'Queja'), ('PR', 'Pregunta'), ('RE', 'Reclamo'), ('SU', 'Sugerencia'), ('FE', 'Felicitación')], max_length=2, verbose_name='Motivo')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('message', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Formulario de contacto',
                'verbose_name_plural': 'Formularios de contacto',
            },
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_type', models.CharField(choices=[('TC', 'Términos y condiciones'), ('PP', 'Políticas de privacidad'), ('CO', 'Cookies')], max_length=2, unique=True, verbose_name='Tipo de Política')),
                ('text', models.TextField(verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Politica',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre Sector')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_sectors', to='manager.City', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='TransitDepartmentPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runt', models.IntegerField(verbose_name='Precio RUNT')),
                ('printing', models.IntegerField(verbose_name='Precio impresion')),
                ('other', models.IntegerField(verbose_name='Otros valores')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Adminsitración Recaudo Organismo de transito',
                'verbose_name_plural': 'Administración Recaudos Organismos de transito',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_cities', to='manager.State', verbose_name='Departamento'),
        ),
    ]
