# Generated by Django 2.1.1 on 2018-10-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20180914_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRCAdminPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_sicov', models.CharField(max_length=255, verbose_name='Precio PIN SICOV')),
                ('recaudo', models.CharField(max_length=255, verbose_name='Precio Recaudo Banco')),
            ],
            options={
                'verbose_name': 'Adminsitración Recaudo CRC',
                'verbose_name_plural': 'Administración Recaudos CRC',
            },
        ),
    ]
