# Generated by Django 2.1.1 on 2018-10-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_crcadminprices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crcadminprices',
            name='pin_sicov',
            field=models.IntegerField(verbose_name='Precio PIN SICOV'),
        ),
        migrations.AlterField(
            model_name='crcadminprices',
            name='recaudo',
            field=models.IntegerField(verbose_name='Precio Recaudo Banco'),
        ),
    ]
