# Generated by Django 2.1.1 on 2018-10-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crcadminprices',
            options={'verbose_name': 'Adminsitración Recaudo', 'verbose_name_plural': 'Administración Recaudos'},
        ),
        migrations.AddField(
            model_name='crcadminprices',
            name='company',
            field=models.CharField(choices=[('CEA', 'Centro de enseñanza automovilístico'), ('CRC', 'Centro de reconocimiento de conductores')], default='CRC', max_length=3, verbose_name='Compañía'),
        ),
        migrations.AddField(
            model_name='crcadminprices',
            name='supplier',
            field=models.CharField(default='', max_length=255, verbose_name='Proveedor'),
        ),
    ]
