# Generated by Django 2.1.1 on 2018-10-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20181016_0953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CRCAdminPrices',
            new_name='CompaniesAdminPrices',
        ),
    ]
