# Generated by Django 2.1.1 on 2018-10-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20181016_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('email', models.CharField(max_length=255, verbose_name='Correo')),
                ('contact_type', models.CharField(choices=[('PE', 'Petición'), ('QU', 'Queja'), ('PR', 'Pregunta'), ('RE', 'Reclamo'), ('SU', 'Sugerencia'), ('FE', 'Felicitación')], max_length=2, verbose_name='Motivo')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('message', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Formulario de contacto',
                'verbose_name_plural': 'Formularios de contacto',
            },
        ),
    ]
