# Generated by Django 2.1.1 on 2018-11-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitDepartmentPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runt', models.IntegerField(verbose_name='Precio RUNT')),
                ('printing', models.IntegerField(verbose_name='Precio impresion')),
                ('other', models.IntegerField(verbose_name='Otros valores')),
            ],
            options={
                'verbose_name': 'Adminsitración Recaudo Organismo de transito',
                'verbose_name_plural': 'Administración Recaudos Organismos de transito',
            },
        ),
    ]
