# Generated by Django 2.1.1 on 2018-11-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_transitdepartmentprices'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitdepartmentprices',
            name='name',
            field=models.CharField(default='REcaudo', max_length=255, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
